### ISSUE TITLE
I don't think you can pattern-match on Rationals

### ISSUE THREAD

**Issue by newlandsvalley** [imeckler/ratio#2]
I want to be able to write (for example):

```
isZero : Rational -> Bool
isZero r =
  case r of
    Ratio 0 _ ->
       True
    _ ->
       False
```

but you don't export the Ratio constructor.  Is there a reason for it? (Incidentally, if you wanted to do this, there is nothing stopping you use Rational for both the type and the constructor).

**Comment by imeckler** [comment]
Yes, this is on purpose so that you can't construct invalid rational values (the numerator and denominator should always be relatively prime). You have access to the value via numerator, denominator, split and toFloat. If you want to check if something is zero, just do

``` elm
isZero r = 0 == Ratio.numerator r
```

**Comment by newlandsvalley** [comment]
I thought you might say this.  My use case is this one.

```
type Primitive a =
      Note Rational a
    | Rest Rational

type Music a =
   Prim (Primitive a)
   | .....
```

I want to write a function that identifies zero length Rationals which are used to represent durations of musical notes or rests:

```
lineToList : Music a -> List (Music a)
lineToList m =
  case m of
    (Prim (Rest (Rational 0 _))) -> 
        []
    ......
```

**Comment by imeckler** [comment]
Maybe I am misunderstanding, but I believe you don't need to expose the constructor for this. You can still do

``` elm
lineToList : Music a -> List (Music a)
lineToList m =
  case m of
    (Prim (Rest r)) -> if numerator r == 0 then [] else ...
    ......
```

**Comment by newlandsvalley** [comment]
No - you're quite right.  I just find it clumsy.  Actually, I've changed my mind about exposing the constructor after experimenting for a bit - but for a different reason.  Are you aware that you can define Rationals with (for example):

```
over 1 (-4) 
over (-1) (-4)
```

I think that _over_ should normalise these so that the denominator is always positive.
