### ISSUE TITLE
Update for Elm 0.18?

### ISSUE THREAD

**Issue by jvoigtlaender** [imeckler/ratio#5]
I guess the update will be very simple, just bumping dependency bounds and getting rid of infix function use.

Want help, a PR?

**Comment by newlandsvalley** [comment]
Can I reiterate what @jvoigtlaender asked?  I have a number of projects that depend on ratio.

**Comment by jvoigtlaender** [comment]
@imeckler, can you say whether you plan to continue maintaining this package?

Otherwise, do you have an opinion on having the package be continued and further maintained by the @elm-community organization?

**Comment by imeckler** [comment]
Happy to have the package continued and maintained by elm-community. Let me know what steps I need to take to make that happen.

**Comment by jvoigtlaender** [comment]
@imeckler, http://package.elm-lang.org/packages/elm-community/ratio/1.0.0 now exists and is equivalent to http://package.elm-lang.org/packages/imeckler/ratio/2.0.1. One last thing you could do is publish a `2.0.2` version of your package that contains a pointer to http://package.elm-lang.org/packages/elm-community/ratio in the README. 

Something like at the top of https://github.com/elm-community/elm-webgl/blob/master/README.md.
